---

- name: create openvpn log directory
  file:
    state: directory
    path: '{{ openvpn_logging.directory }}'
    owner: "{{ openvpn_owner }}"
    group: "{{ openvpn_group }}"
    mode: 0775
  tags:
    - setup
    - openvpn

- name: create client key directory
  file:
    state: directory
    path: '{{ openvpn_directory }}/keys'
    owner: "{{ openvpn_owner }}"
    group: "{{ openvpn_group }}"
    mode: 0755
  tags:
    - setup
    - openvpn

- name: openvpn server
  block:
    - name: configure openvpn server
      include_tasks: configure/server.yml

    - name: configure openvpn client users
      include_tasks: configure/client_users.yml
  when:
    - openvpn_type == "server"

- name: openvpn client
  block:
    - name: configure openvpn client
      include_tasks: configure/client.yml
  when:
    - openvpn_type == "client"

- name: change rights for created files
  file:
    state: directory
    path: "{{ openvpn_directory }}/keys"
    owner: "{{ openvpn_owner }}"
    group: "{{ openvpn_group }}"
    recurse: true

- name: flush handlers at this point to avoid double restart
  meta: flush_handlers

...
