---

- name: install package
  package:
    name: "{{ openvpn_packages }}"
    state: present
  tags:
    - openvpn
    - openvpn_install

- name: handle easy-rsa
  block:
    - name: link easy-rsa into /etc
      file:
        state: link
        src: /usr/share/easy-rsa
        dest: "{{ openvpn_easyrsa.directory }}"

    - name: link easyrsa binary into /bin
      file:
        state: link
        src: "{{ openvpn_easyrsa.directory }}/easyrsa"
        dest: /bin/easyrsa

  when:
    - ansible_os_family | lower == "debian"

- name: openrc
  block:
    - name: copy up.sh to system
      copy:
        src: up.sh
        dest: /etc/openvpn/
        mode: 0750

    - name: copy down.sh to system
      copy:
        src: down.sh
        dest: /etc/openvpn/
        mode: 0750

  when:
    - ansible_service_mgr | lower == "openrc"
    - not openvpn_type == "server"

...
