---

- name: install package
  ansible.builtin.package:
    name: "{{ openvpn_packages }}"
    state: present
  tags:
    - openvpn
    - openvpn_install

- name: get openvpn _version
  openvpn_version:
  register: openvpn_version

- name: create custom fact file
  bodsch.core.facts:
    name: openvpn
    facts:
      version: "{{ openvpn_version.version }}"

- name: gathering facts now
  ansible.builtin.setup:

- name: handle easy-rsa
  when:
    - ansible_os_family | lower == "debian"
  block:
    - name: link easy-rsa into /etc
      ansible.builtin.file:
        state: link
        src: /usr/share/easy-rsa
        dest: "{{ openvpn_easyrsa.directory }}"

    - name: link easyrsa binary into /bin
      ansible.builtin.file:
        state: link
        src: "{{ openvpn_easyrsa.directory }}/easyrsa"
        dest: /bin/easyrsa

- name: openrc
  when:
    - ansible_service_mgr | lower == "openrc"
    - not openvpn_type == "server"
  block:
    - name: copy up.sh to system
      ansible.builtin.copy:
        src: up.sh
        dest: /etc/openvpn/
        mode: 0750

    - name: copy down.sh to system
      ansible.builtin.copy:
        src: down.sh
        dest: /etc/openvpn/
        mode: 0750

...
