---

- name: preparement
  ansible.builtin.include_tasks: prepare.yml

- name: install
  ansible.builtin.include_tasks: install.yml

- name: configure
  ansible.builtin.include_tasks: configure.yml

- name: service
  ansible.builtin.include_tasks: service.yml

...
