---

- name: include OS specific configuration
  ansible.builtin.include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      paths:
        - "vars"
      files:
        # eg. debian-10 / ubuntu-20 / centos-8 / oraclelinux-8
        - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version }}.yml"
        # eg. archlinux-systemd / archlinux-openrc
        - "{{ ansible_distribution | lower }}-{{ ansible_service_mgr | lower }}.yml"
        # eg. debian / ubuntu / centos / oraclelinux
        - "{{ ansible_distribution | lower }}.yml"
        # eg. redhat / debian
        - "{{ ansible_os_family | lower }}.yml"
        # artixlinux
        - "{{ ansible_os_family | lower | replace(' ', '') }}.yml"
        - default.yml
      skip: true

- name: detect docker environment
  ansible.builtin.set_fact:
    is_docker_guest: "{{
      ansible_virtualization_role | default('host') == 'guest' and
      ansible_virtualization_type | default('none') == 'docker' }}"

- name: install dependencies
  ansible.builtin.package:
    name: "{{ openvpn_dependencies }}"
    state: present

- name: gathering facts now
  ansible.builtin.setup:

- name: merge openvpn configuration between defaults and custom
  ansible.builtin.set_fact:
    openvpn_service: "{{ openvpn_defaults_service | combine(openvpn_service, recursive=True) }}"
    openvpn_logging: "{{ openvpn_defaults_logging | combine(openvpn_logging, recursive=True) }}"
    openvpn_easyrsa: "{{ openvpn_defaults_easyrsa | combine(openvpn_easyrsa, recursive=True) }}"
    openvpn_certificate: "{{ openvpn_defaults_certificate | combine(openvpn_certificate, recursive=True) }}"
    openvpn_server: "{{ openvpn_defaults_server | combine(openvpn_server, recursive=True) }}"
    openvpn_push: "{{ openvpn_defaults_push | combine(openvpn_push, recursive=True) }}"

...
