---

- name: start and enable service
  ansible.builtin.service:
    name: "{{ openvpn_service_name }}"
    state: "{{ openvpn_service.state | default('started') }}"
    enabled: "{{ openvpn_service.enabled | default(true) | bool }}"
  ignore_errors: "{{ 'true' if ansible_service_mgr | lower == 'openrc' else 'false' }}"
  failed_when: false
  tags:
    - openvpn
    - start-enable-service
  when:
    - openvpn_type == "server" or
      (openvpn_client_name is defined and openvpn_client_name | string | length > 0)

...
