---

- name: systemctl daemon-reload
  become: true
  systemd:
    daemon_reload: true
    force: true

- name: restart openvpn-server
  service:
    name: "{{ openvpn_service_name }}"
    state: restarted

- name: restart openvpn-client
  service:
    name: "{{ openvpn_service_name }}"
    state: restarted

#   when:
#     - ansible_service_mgr | lower == "systemd"
#     - openvpn_type == "server"
#
# - name: restart openvpn-server
#   service:
#     name: openvpn
#     state: restarted
#   when:
#     - ansible_service_mgr | lower == "openrc"

...
