---

- name: create temporary transfer directory on ansible controller
  become: false
  delegate_to: localhost
  file:
    path: "{{ openvpn_local_tmp_directory }}"
    state: directory
    mode: 0750

- name: create openvpn static client configs
  include_tasks: configure/static_client_instances.yml
  loop: "{{ openvpn_static_clients }}"
  loop_control:
    index_var: index
    loop_var: client
    label: "client: {{ client.name }}"
  when:
    - client is defined
    # - client.name | string | length > 0

- name: define static client IPs
  template:
    src: openvpn/server/ipp.txt.j2
    dest: /etc/openvpn/ipp.txt
    mode: 0644
  when:
    (openvpn_static_clients is defined and
     openvpn_static_clients | count > 0) or
    (openvpn_mobile_clients is defined and
     openvpn_mobile_clients | count > 0)
...
