---

- name: create temporary transfer directory on ansible controller
  become: false
  delegate_to: localhost
  file:
    path: "{{ openvpn_local_tmp_directory }}"
    state: directory
    mode: 0750

- name: create openvpn static client configs
  include_tasks: configure/static_client_instances.yml
  loop: "{{ openvpn_persistent_pool }}"
  loop_control:
    index_var: index
    loop_var: client
    label: "client: {{ client.name }}"
  when:
    - client is defined
    # - client.name | string | length > 0

...
