---
name: publish

on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - "CI"
    #branches:
    #  - main
    types:
      - completed

jobs:

  publish:
    if: ${{ github.ref == 'refs/heads/main' && github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-20.04
    steps:
      - name: galaxy
        uses: robertdebock/galaxy-action@1.2.1
        with:
          galaxy_api_key: ${{ secrets.galaxy_api_key }}
          git_branch: main